Repository nicklashersen/numpy, pull requests merged in 2019-02, with the labels that each got.

#3 Doc: Add ten python functions with highest CNN. #1
  README.md
Labels: documentation

#8 Doc: Add manual CNN calculation for add_data_files #7
  README.md
  doc_resources/add_data_files.png
Labels: documentation

#17 Add on-boarding question answers
  README.md
Labels: documentation

#15 Function list with lower CCNs that the current ones
  README.md
Labels: fix

#30 Refactor add_data_dir
  numpy/distutils/misc_util.py
Labels: refactoring

#29 Refactor add_data_files
  numpy/distutils/misc_util.py
Labels: refactoring

#33 Refactor issue #20 #21 #22
  numpy/distutils/ccompiler.py
  numpy/distutils/command/build_src.py
  numpy/distutils/system_info.py
Labels: refactoring

#52 Refactored _exec_command function into multiple subroutines. #25.
  numpy/distutils/exec_command.py
Labels: refactoring

#54 Refactored setup function
  numpy/distutils/core.py
Labels: refactoring

#57 Added tests for get_path function
  numpy/distutils/tests/test_system_info.py
Labels: testing

#53 Refactor get_atlas_info
  numpy/distutils/system_info.py
Labels: refactoring

#58 Add unit tests for two branches in core.setup #46 #47
  numpy/distutils/ccompiler.py
  numpy/distutils/command/build_src.py
  numpy/distutils/core.py
  numpy/distutils/exec_command.py
  numpy/distutils/misc_util.py
  numpy/distutils/system_info.py
  numpy/distutils/tests/test_core.py
Labels: testing

#60 Coverage improvement
  numpy/distutils/tests/test_system_info.py
Labels: enhancement

#67 Added tests for CCompiler_customize when no_cxx is True
  numpy/distutils/tests/test_ccompiler.py
Labels: testing

#62 Implement _exec command unittests
  numpy/distutils/tests/test_exec_command.py
Labels: testing

#63 Implement finalize_options unittests
  numpy/distutils/tests/test_command_build_src.py
Labels: testing

#68 Refactor analyzeline to reduce CCN by 35%
  numpy/f2py/crackfortran.py
Labels: refactoring

#69 Refactor _scalar_str
  numpy/core/_dtype.py
Labels: refactoring

#74 Fixed bug in tests for get_paths on linux
  numpy/distutils/tests/test_system_info.py
Labels: bug

#70 Refactor long_double_representation
  numpy/core/setup_common.py
Labels: refactoring

#75 Fix #65
  numpy/distutils/ccompiler.py
Labels: bug

#77 Added missing documentation for CCompiler_customize tests. Fix #76
  numpy/distutils/tests/test_ccompiler.py
Labels: bug

#72 Refactor analyzevars to reduce CCN by 35%.
  numpy/f2py/crackfortran.py
Labels: refactoring

#79 Test/setup new
  numpy/distutils/system_info.py
  numpy/distutils/tests/test_core.py
  numpy/distutils/tests/test_system_info.py
Labels: testing

#80 Added comments for CCN calculation for finalize_options. Fix #78.
  numpy/distutils/command/build_src.py
Labels: bug

#82 Add manual CCN notation ot add_data_files
  numpy/distutils/misc_util.py
Labels: documentation

#83 Fix: missing return statment in manual CCN calc
  numpy/distutils/misc_util.py
Labels: bug, documentation

#81 Add tests for Unittest long_double_representation resolving issues #50, #51
  numpy/core/tests/test_setup_common.py
Labels: testing

#84 Add test for add_data_dir and add_data_files for typeErrors resolving issues #32, #36
  numpy/distutils/tests/test_misc_util.py
Labels: testing

#86 Add documentation of refactoring
  README.md
Labels: documentation

#87 Add manual CCN calculation for CCompiler_customize
  numpy/distutils/ccompiler.py
Labels: documentation

#91 adds unittest fix #31
  numpy/core/tests/test_dtype.py
Labels: testing

#93 Removed README content that is in report.md
  README.md
Labels: documentation

#98 Update report.md
  report.md
Labels: documentation

#101 Update README.md
  README.md
Labels: documentation

#100 Documentation for get_atlas_version.
  report.md
Labels: documentation

#104 DOC: Add doc for _exec_command
  report.md
Labels: documentation

#106 Update README.md
  README.md
Labels: documentation

#107 Add codecov links to implemented unittests
  report.md
Labels: documentation

#108 Update report.md
  report.md
Labels: documentation
